package it.water.connectors.s3.api;

import it.water.connectors.s3.model.S3ClientConfig;
import it.water.core.api.service.BaseSystemApi;

import java.util.List;
import java.util.Map;

/**
 * 
 * @Generated by Water Generator
 * This interface defines the internally exposed methods allows interaction with them bypassing permission system.
 * 
 */
public interface S3ConnectorsSystemApi extends BaseSystemApi {

    List<String> listObjects(String prefix);

    Map<String, String> getMetadata(String path);

    void uploadFile(String path, byte[] content, Map<String, String> metadata);

    void createDirectory(String path);

    void delete(String path);

    void update(String path, byte[] newContent, Map<String, String> newMetadata);
}