package it.water.connectors.s3.api;

import it.water.core.api.service.BaseApi;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods and allows interaction with them through a permission system.
 *
 */
public interface S3ConnectorsApi extends BaseApi {

}