package it.water.connectors.s3.service;

import it.water.connectors.s3.api.*;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
import it.water.core.service.BaseServiceImpl;
import lombok.*;


/**
 * @Generated by Water Generator
 * Service Api Class for S3Connectors entity.
 *
 */
@FrameworkComponent
public class S3ConnectorsServiceImpl extends BaseServiceImpl implements S3ConnectorsApi {

    @Inject
    @Getter
    @Setter
    private S3ConnectorsSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public S3ConnectorsServiceImpl() {
    }
}
