package it.water.connectors.s3.service;

import it.water.connectors.s3.api.S3ConnectorApi;
import it.water.connectors.s3.api.S3ConnectorSystemApi;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
import it.water.core.service.BaseServiceImpl;
import lombok.*;


/**
 * @Generated by Water Generator
 * Service Api Class for S3Connector entity.
 *
 */
@FrameworkComponent
public class S3ConnectorServiceImpl extends BaseServiceImpl implements S3ConnectorApi {

    @Inject
    @Getter
    @Setter
    private S3ConnectorSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public S3ConnectorServiceImpl() {
    }
}
